[build-system]
requires = [
  "setuptools>=61.0.0",
  "setuptools-scm>=8",
  "wheel",
  "build",
  "kintera>=2.1.0",
  "commux>=0.0.2",
  "torch==2.10.0",
  "ninja",
  ]
build-backend = "setuptools.build_meta"

[project]
name = "snapy"
dynamic = ["version"]
description = "Compressible Finite Volume Solver for Atmospheric Dynamics, Chemistry and Thermodynamics"
authors = [
  { name="Cheng Li", email="chengcli@umich.edu" },
]
license = { text = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "pyyaml",
  "kintera>=2.1.0",
  "commux>=0.0.2",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Natural Language :: English",
  "Programming Language :: C",
  "Programming Language :: C++",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Topic :: Scientific/Engineering :: Atmospheric Science",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Scientific/Engineering :: Astronomy",
]

[project.urls]
Homepage = "https://github.com/chengcli/snapy"
Documentation = "https://snapy.readthedocs.io"

[project.scripts]
pd-combine = "snapy.api.pd_combine:main"
pd-inspect = "snapy.api.pd_inspect:main"


[tool.setuptools]
packages = ["snapy"]
include-package-data = false
script-files = ["api/pd-run", "api/slurm.sbatch"]

[tool.setuptools.package-data]
"snapy" = [
  "snap/**/*",
  "lib/*.so",
  "lib/*.so.*",
  "lib/*.dylib",
  "lib/ucx/*.so",
  "lib/ucx/*.so.*",
  "snapy/*.pyi",
  "py.typed",
  "api/*",
]

[tool.setuptools.exclude-package-data]
"snapy" = ["csrc/**/*"]

[tool.setuptools_scm]
fallback_version = "0.0.0"
