name: Continuous Integration

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

env:
  PYTHON_VERSION: "3.11"
  BUILD_TYPE: Release

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install style checkers
        run: pip install --user cpplint cppcheck clang-format==20.1.4

      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  build-and-test:
    needs: pre-commit
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Install Python dependencies
        run: |
          pip install wheel numpy pyyaml pytest netcdf4
          pip install 'torch==2.10.0'
          pip install 'kintera>=2.1.0'

      - name: Install NetCDF
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y libnetcdf-dev nco autoconf automake libtool pkg-config
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            HOMEBREW_NO_AUTO_UPDATE=1 brew install netcdf nco
          fi

      - name: Configure CMake
        run: |
          cmake -B ${{ github.workspace }}/build \
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
                -DNETCDF=ON \
                -DBUILD_TESTS=ON

      - name: Build
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --parallel 4
          else
            cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --parallel 3
          fi

      - name: Install the project
        run: pip install --no-build-isolation --no-deps .

      - name: Run C++ & Pybind tests
        run: |
          cd ${{ github.workspace }}/build/tests
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            ctest --output-on-failure -R '^(test_.*|test_exchange_decomp|test_straka.*|test_shallow_.*)$'
          else
            ctest --output-on-failure -E '^(test_straka|test_shallow_xy|test_shallow_splash|test_shock_cpu|test_run_hydro_cpu)$'
          fi
